---
title: "卒論の書き方と留意事項"
---

## 本文
1. 句読点は，原則として，全角カンマ「，」，全角ピリオド「．」を使用する．^[「、。」を使った場合は，Replace All 機能を使えば，一括変換できる．「word Replace All」，「overleaf relace all」などで検索すると，方法が見つかる．]
2. できるだけ箇条書きにはしない．
3. 「私」等の一人称は使用しない．

## 数式
1. 文章中に数式を入れるとき，数式環境を使う．例えば，$y = ax + b$ のように記述する．
2. $\max$，$\min$，$\sin$，$\cos$，$\log$ などの関数は，イタリック体ではなくローマン体で記述する．例えば，$y = \sin x$ のように記述する．
3. 記号の表記は統一する．以下にガイドラインを示す．

| |表記例|
|-|-|
|スカラー|$a, b, c$|
|ベクトル|$\mathbf{x}, \mathbf{y}$|
|確率変数|$X, Y$|
|集合|$A, B$ または $\mathcal{A}, \mathcal{B}$|
|行列|$\mathbf{A}, \mathbf{B}$|



## 図表
1. 図表を使うときは，必ず本文でその図表に言及しておく．
2. 図表中の文字は，本文と同じ程度の大きさにする．
3. 卒論概要は印刷時はモノクロになるため，図において色での判別は行わないこと．
4. 原則，図表の転載は禁止する．やむを得ず転載する場合は，当該論文の著作権者の掲載許可を得るとともに，出典を明記する．^[[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)などのライセンスで公開されている図表については，著作権者の許可を得る必要はないが，出典を明記すること．]

## 用語
1. 用語を統一する．例えば，「深層学習」と「ディープラーニング」は同じ意味であるため，どちらか一方に統一する．
2. 標準的に用いられている用語を使用する．例えば，「ニューラルネットワーク」は「神経回路網」とせず，「ニューラルネットワーク」を使用する．

## 略語
1. 略語を用いる場合は，初出時に正式名称を明記する．
2. 本文中に一度しか記載のない名称は，略語・略称表記は不要．

## Overleaf の注意点
1. 段落の改行は，`\\` ではなく空行を入れることで行う．
2. エラーが発生した場合は，エラーメッセージをよく読み，デバッグする．
3. ウェブサイトを引用する場合は，`@misc` を回避策として使用する．詳細は[こちら](https://bibtex.eu/ja/faq/how-can-i-use-bibtex-to-cite-a-website/)を参照のこと．

## 類似性レポート

学位論文に対してTurnitinによる類似性チェックを実施します．Turnitinの類似性レポートの読み方や，類似箇所の修正方法については，以下のサイトを参考にしてください．

[Turnitin類似性レポートの読み方と修正方法](https://turnitin-checker.com/ja-JP/how-to-read-turnitin-similarity-report.html)

## スケジュール

- 論文執筆開始: 11月1日（1日1ページ程度を目安に執筆を進めること）
- 第一案提出: 12月1日
- 第二案提出: 12月末まで
- 最終チェック: 1月上旬
- 卒論概要の作成: 卒業論文最終版完成後すぐ
- 論文・概要提出: 1月中旬

## 文献検索

- [CiNii](https://cir.nii.ac.jp/)
- [Google Scholar](https://scholar.google.com/)

### 学位論文

- [京都大学 学位論文](http://hdl.handle.net/2433/48884)
- [大阪大学 博士論文検索](https://ir.library.osaka-u.ac.jp/repo/ouka/thesis/)

## 論文の構成
